[2024-07-15T04:56:13.866+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T04:56:13.883+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.merge_data manual__2024-07-15T04:54:02.957820+00:00 [queued]>
[2024-07-15T04:56:13.888+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.merge_data manual__2024-07-15T04:54:02.957820+00:00 [queued]>
[2024-07-15T04:56:13.889+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T04:56:13.906+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): merge_data> on 2024-07-15 04:54:02.957820+00:00
[2024-07-15T04:56:13.915+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-15T04:56:13.915+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'merge_data', 'manual__2024-07-15T04:54:02.957820+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpnc01c3hx']
[2024-07-15T04:56:13.917+0000] {standard_task_runner.py:63} INFO - Started process 92 to run task
[2024-07-15T04:56:13.917+0000] {standard_task_runner.py:91} INFO - Job 237: Subtask merge_data
[2024-07-15T04:56:13.956+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.merge_data manual__2024-07-15T04:54:02.957820+00:00 [running]> on host 37d6808b0cee
[2024-07-15T04:56:14.038+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T04:54:02.957820+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-15T04:54:02.957820+00:00'
[2024-07-15T04:56:14.039+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T04:56:19.962+0000] {demo.py:60} INFO - Data Merged
[2024-07-15T04:56:20.161+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-15T04:56:20.162+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T04:56:20.173+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=merge_data, run_id=manual__2024-07-15T04:54:02.957820+00:00, execution_date=20240715T045402, start_date=20240715T045613, end_date=20240715T045620
[2024-07-15T04:56:20.244+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-15T04:56:20.272+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-15T04:56:20.282+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
