[2024-07-15T04:40:06.160+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T04:40:06.197+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.merge_data manual__2024-07-15T04:37:49.621349+00:00 [queued]>
[2024-07-15T04:40:06.222+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.merge_data manual__2024-07-15T04:37:49.621349+00:00 [queued]>
[2024-07-15T04:40:06.223+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T04:40:06.254+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): merge_data> on 2024-07-15 04:37:49.621349+00:00
[2024-07-15T04:40:06.279+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=252) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-15T04:40:06.284+0000] {standard_task_runner.py:63} INFO - Started process 254 to run task
[2024-07-15T04:40:06.283+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'merge_data', 'manual__2024-07-15T04:37:49.621349+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpfscwzbfv']
[2024-07-15T04:40:06.290+0000] {standard_task_runner.py:91} INFO - Job 225: Subtask merge_data
[2024-07-15T04:40:06.394+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.merge_data manual__2024-07-15T04:37:49.621349+00:00 [running]> on host 37d6808b0cee
[2024-07-15T04:40:06.575+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T04:37:49.621349+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-15T04:37:49.621349+00:00'
[2024-07-15T04:40:06.576+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T04:40:15.094+0000] {demo.py:62} INFO - Data Merged
[2024-07-15T04:40:15.329+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-15T04:40:15.330+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T04:40:15.340+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=merge_data, run_id=manual__2024-07-15T04:37:49.621349+00:00, execution_date=20240715T043749, start_date=20240715T044006, end_date=20240715T044015
[2024-07-15T04:40:15.396+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-15T04:40:15.414+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-15T04:40:15.437+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
