[2024-07-15T04:25:33.214+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T04:25:33.233+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.clean_data scheduled__2024-07-14T00:00:00+00:00 [queued]>
[2024-07-15T04:25:33.239+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.clean_data scheduled__2024-07-14T00:00:00+00:00 [queued]>
[2024-07-15T04:25:33.239+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T04:25:33.258+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clean_data> on 2024-07-14 00:00:00+00:00
[2024-07-15T04:25:33.269+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=58) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-15T04:25:33.271+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'clean_data', 'scheduled__2024-07-14T00:00:00+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpa2esfsab']
[2024-07-15T04:25:33.272+0000] {standard_task_runner.py:91} INFO - Job 218: Subtask clean_data
[2024-07-15T04:25:33.278+0000] {standard_task_runner.py:63} INFO - Started process 60 to run task
[2024-07-15T04:25:33.320+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.clean_data scheduled__2024-07-14T00:00:00+00:00 [running]> on host 37d6808b0cee
[2024-07-15T04:25:33.398+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T00:00:00+00:00'
[2024-07-15T04:25:33.399+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T04:25:33.409+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T04:25:33.409+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Company'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo.py", line 31, in clean_data
    df_xlsx['Company'] = df_xlsx['Company'].apply(lambda x: process.extractOne(x, df_csv['Company'])[0])
                         ~~~~~~~^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'Company'
[2024-07-15T04:25:33.431+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=clean_data, run_id=scheduled__2024-07-14T00:00:00+00:00, execution_date=20240714T000000, start_date=20240715T042533, end_date=20240715T042533
[2024-07-15T04:25:33.446+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 218 for task clean_data ('Company'; 60)
[2024-07-15T04:25:33.457+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T04:25:33.475+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T04:25:33.483+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T16:54:25.932+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:54:26.136+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.clean_data scheduled__2024-07-14T00:00:00+00:00 [queued]>
[2024-07-22T16:54:26.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.clean_data scheduled__2024-07-14T00:00:00+00:00 [queued]>
[2024-07-22T16:54:26.232+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-22T16:54:26.412+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clean_data> on 2024-07-14 00:00:00+00:00
[2024-07-22T16:54:26.482+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=135) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:54:26.513+0000] {standard_task_runner.py:63} INFO - Started process 157 to run task
[2024-07-22T16:54:26.527+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'clean_data', 'scheduled__2024-07-14T00:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpqk3gae9t']
[2024-07-22T16:54:26.535+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask clean_data
[2024-07-22T16:54:26.793+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.clean_data scheduled__2024-07-14T00:00:00+00:00 [running]> on host ada6cb1e64b1
[2024-07-22T16:54:27.371+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T00:00:00+00:00'
[2024-07-22T16:54:27.384+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:57:04.666+0000] {demo.py:52} INFO - Data Cleaned and Preprocessed
[2024-07-22T16:57:04.686+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T16:57:04.687+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:57:04.745+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=clean_data, run_id=scheduled__2024-07-14T00:00:00+00:00, execution_date=20240714T000000, start_date=20240722T165426, end_date=20240722T165704
[2024-07-22T16:57:04.863+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-22T16:57:04.901+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
